In [ ]:
from sklearn.decomposition import PCA
import pandas as pd
import numpy as np

# Ejemplo de datos
datos = pd.read_csv("Datos.csv")
X = pd.DataFrame(datos.drop(columns=["y"]))
y = datos["y"]

y = y.astype('category')
X['x1'] = X['x1'].astype('category')
X['x2'] = X['x2'].astype('category')
X['x3'] = X['x3'].astype('category')
X['x4'] = X['x4'].astype('category')
X['x5'] = X['x5'].astype('category')


# Crear una instancia de PCA con 2 componentes principales
pca = PCA(n_components=5, whiten=False)

# Ajustar y transformar los datos
data_pca = pca.fit_transform(X_centered)

print("Datos originales:")
print(X)
print("Datos transformados por PCA:")
print(data_pca)

Datos originales:
   x1 x2 x3 x4 x5
0   0  0  0  0  0
1   0  0  0  0  1
2   0  0  1  1  0
3   0  0  1  1  1
4   0  1  0  1  0
.. .. .. .. .. ..
95  0  1  0  1  0
96  1  0  0  0  1
97  0  0  1  1  0
98  0  1  0  1  1
99  0  1  1  0  1

[100 rows x 5 columns]
Datos transformados por PCA:
[[ 0.36263251  0.06752031  0.19443242 -0.68393184 -0.74690826]
 [ 0.31544918 -0.41993761 -0.52591195 -0.19897603 -0.66893152]
 [ 0.01091164  0.44308864  0.77073723  0.48014172 -0.52771341]
 [-0.03627169 -0.04436928  0.05039287  0.96509752 -0.44973667]
 [-0.34583138  0.97004397 -0.05998604 -0.3371179  -0.04084786]
 [-0.39301472  0.48258605 -0.7803304   0.1478379   0.03712888]
 [-0.65210634 -0.18697064  0.68304316 -0.43788723  0.03171939]
 [-0.69928967 -0.67442856 -0.03730121  0.04706857  0.10969613]
 [ 1.00976244  0.00460468  0.29309313 -0.65872516  0.00601616]
 [ 0.9625791  -0.48285324 -0.42725123 -0.17376936  0.0839929 ]
 [ 0.65804156  0.38017301  0.86939795  0.50534839  0.225211  ]
 [ 0.61085823 -0.107